### PR TITLE
Use binary prefix for file size

### PR DESCRIPTION
**Pull request by fabianfreyer**
[Binary prefixes](https://en.wikipedia.org/wiki/Binary_prefix) make more sense for file sizes than decimal ones.

Builds on top of the ` refactor` branch.

### CODE REVIEW

**Comment by Arcterus** [comment]
Would you mind running `rustfmt` configured to use three spaces rather than four?  Other than that, I'm fine with this.

**Comment by fabianfreyer** [comment]
Sure! Should I include the respective rustfmt.toml?

**Comment by Arcterus** [comment]
Yeah, that would be great.  Thanks!

**Comment by fabianfreyer** [comment]
done and rebased :)

**Comment by Arcterus** [comment]
Thanks :)

**Pull request merged**
